#!/usr/bin/env python3
"""
claims_index.py  --  which claim IDs exist, and what can make each one fail.

    python claims_index.py              # the index, by evidence class
    python claims_index.py status       # index JOINED with the register
    python claims_index.py salvage      # what is reusable from being wrong
    python claims_index.py unregistered # claims with no recorded statement
    python claims_index.py prose        # claims nothing can fail on
    python claims_index.py show FCL-4   # one claim, every site
    python claims_index.py families     # counts per prefix

Stdlib only. Derived by scanning -- there is no hand-maintained list here to
drift out of date, which is the whole point.

=====================================================================
WHY DERIVED, AND WHY BY EVIDENCE CLASS
=====================================================================
This started as bookkeeping: PRINCIPLES.json cites instance tags like
"KEA-7", nothing checked that they pointed at anything, and 13 of 36 turned
out to be shorthand invented at writing time that resolves nowhere.

The obvious fix -- a hand-written register mapping tags to claims -- would
have been a second authority over the same facts, which is P-DUPLICATE-
AUTHORITY, one of the shapes this repo already catalogued. So the index is
scanned instead.

Inferring "where is this claim DEFINED" from prose formatting was tried and
abandoned: it marked VAC-1 as defined inside a docstring that merely mentions
it, and missed KEA-7 entirely. A heuristic over free text is exactly the kind
of thing that looks reasonable and cannot be falsified.

So the classification is not about where a claim is written. It is about what
can make it FAIL, which is the only question this archive has ever cared
about:

    FALSIFIER   a runnable report calls check("ID: ...") and exits nonzero
    NAMED_IN_TEST
                a file under tests/ mentions it. NAMING IS NOT ASSERTING --
                this detects that a suite knows the id exists, which is
                weaker than a test that can fail on it, and the class is
                named for what it actually measures rather than what would
                be nicer to claim.
    REGISTER    a claim-register table row carries it
    PROSE       it is written down, and nothing executes against it

PROSE is not an error. Some claims are bench work nobody has run, and some
are definitions. It is a state worth being able to list, which is what
`claims_index.py prose` is for.

One artifact worth knowing about: this scanner reads the whole tree including
its own tests, so an id written as a test fixture appears in the index as a
real claim. tests/test_claims_index.py therefore builds its fake ids at
runtime rather than writing them as literals. A tool that scans everything
scans itself.
"""
import collections
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))

ID = r'[A-Z][A-Z0-9]{1,7}-[0-9]{1,2}[a-z]?'
ID_RX = re.compile(r'(?<![\w-])(%s)(?![\w-])' % ID)

# Prefixes that match the ID shape but are not claims of this archive.
NOT_CLAIMS = {"CC0", "CC", "BY", "SA", "ND", "ISO", "UTF", "RFC", "IEEE",
              "ASTM", "SI", "MIT", "GPL", "LGPL", "SP", "NIST", "ANSI",
              "JIS", "DIN", "EN", "IEC", "MIL", "STD", "PEP", "RGB", "SHA",
              "MD", "AES", "RSA", "USB", "I2C", "SPI", "TTL", "CMOS"}

FALSIFIER_RX = re.compile(r'check\(\s*["\'](%s)\b' % ID)
REGISTER = os.path.join(ROOT, "CLAIMS_REGISTER.json")
STATUSES = ("live", "dead", "open", "superseded")

# A claim dies OF something, and the cause decides what is recyclable. Loaded
# from the register so the two cannot drift apart.
def causes(path=None):
    p = path or REGISTER
    if not os.path.exists(p):
        return {}
    with open(p, encoding="utf-8") as fh:
        return json.load(fh).get("causes", {})

REGISTER_RX = re.compile(r'^\s*\|\s*(%s)\s*\|\s*\S' % ID, re.M)

SKIP_DIRS = {".git", "__pycache__", "node_modules", ".pytest_cache",
             "scratchpad", "legacy"}

# This file and its suite talk ABOUT claim ids, so their fixtures would be
# indexed as claims. A scanner that reads the whole tree reads itself: the
# first version of the suite wrote "FNV-1a" as a literal and thereby created
# an FNV claim family. Excluded, and only these two -- CLAUDE.md and
# PRINCIPLES.json also discuss ids, but they discuss REAL ones.
SKIP_FILES = {"claims_index.py", os.path.join("tests", "test_claims_index.py")}

# Anything this tool generated is derived, not a source. Without this the
# rendered CLAIMS.md tables were read back in and their markdown rows counted
# as register entries -- the index citing its own output as evidence.
GENERATED_MARK = "GENERATED by claims_index.py"
EXT = (".py", ".md", ".json", ".txt", ".ino", ".c", ".h", ".yaml", ".yml")

CLASSES = ("FALSIFIER", "NAMED_IN_TEST", "REGISTER", "PROSE")


def _files(root=ROOT):
    for base, dirs, names in os.walk(root):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for n in names:
            if not n.endswith(EXT):
                continue
            rel = os.path.relpath(os.path.join(base, n), root)
            if rel not in SKIP_FILES:
                yield rel


def scan(root=ROOT):
    """claim id -> {class -> sorted files}. Two passes over the tree.

    The second pass exists because a Python identifier cannot contain a
    hyphen, so a suite naming a claim in a class name writes TestR2_8, not
    R2-8, and the first version of this scanner could not see any of them.
    It reported R2-8 as PROSE while tests/test_transient_suppression.py had a
    whole TestR2_8WritePulseAuthority class -- and the register check caught
    it by refusing to record a live claim nothing could falsify.

    The underscore form is only matched for families the hyphen form already
    established, so FIG_2 and PART_3 do not become claims.
    """
    sites = collections.defaultdict(lambda: collections.defaultdict(set))
    texts = {}
    for rel in _files(root):
        try:
            with open(os.path.join(root, rel), encoding="utf-8",
                      errors="ignore") as fh:
                text = fh.read()
        except OSError:
            continue
        if GENERATED_MARK in text[:400]:
            continue
        is_test = rel.startswith("tests" + os.sep) or "test_" in os.path.basename(rel)
        falsifiers = set(FALSIFIER_RX.findall(text))
        registers = set(REGISTER_RX.findall(text))
        for cid in set(ID_RX.findall(text)):
            if cid.split("-")[0] in NOT_CLAIMS:
                continue
            if cid in falsifiers:
                sites[cid]["FALSIFIER"].add(rel)
            if cid in registers:
                sites[cid]["REGISTER"].add(rel)
            if is_test:
                sites[cid]["NAMED_IN_TEST"].add(rel)
            sites[cid]["PROSE"].add(rel)
        texts[rel] = (text, is_test)

    fams = {c.split("-")[0] for c, d in sites.items()
            if d.get("FALSIFIER") or d.get("NAMED_IN_TEST")}
    if fams:
        # NOT (?<![\w]): in a class name TestR2_8 the family is preceded by
        # a lowercase letter. Blocking only uppercase and digits keeps
        # XR2_8 out while letting TestR2_8 in.
        under = re.compile(r'(?<![A-Z0-9])(%s)_([0-9]{1,2})(?![0-9])'
                           % "|".join(sorted(map(re.escape, fams))))
        for rel, (text, is_test) in texts.items():
            for fam, num in set(under.findall(text)):
                cid = "%s-%s" % (fam, num)
                if is_test:
                    sites[cid]["NAMED_IN_TEST"].add(rel)
                sites[cid]["PROSE"].add(rel)
    full = {k: {c: sorted(v) for c, v in d.items()} for k, d in sites.items()}
    fams = claim_families(full)
    return {k: v for k, v in full.items() if k.split("-")[0] in fams}


def claim_families(index):
    """Prefixes with at least one member something can fail on.

    Derived, not maintained. A denylist of licenses and standards would need
    extending every time a new one appeared, and would be wrong silently in
    between; this rule says a family is a claim family when this archive has
    pointed executable machinery at some member of it. FNV-1a, AGPL-3 and FR-4
    drop out because nothing tests them -- they are a hash, a licence and a
    PCB laminate.
    """
    fams = set()
    for cid, d in index.items():
        if d.get("FALSIFIER") or d.get("NAMED_IN_TEST"):
            fams.add(cid.split("-")[0])
    return fams


def evidence(cid, index):
    """The strongest class of thing that can make this claim fail."""
    d = index.get(cid)
    if not d:
        return None
    for c in CLASSES:
        if d.get(c):
            return c
    return "PROSE"


def index_by_class(index):
    out = collections.defaultdict(list)
    for cid in index:
        out[evidence(cid, index)].append(cid)
    return {c: sorted(out[c]) for c in CLASSES if out[c]}


def resolve(tag, index):
    """Does this tag name a real claim, and what backs it?"""
    if tag not in index:
        return {"tag": tag, "known": False, "evidence": None, "files": []}
    return {"tag": tag, "known": True, "evidence": evidence(tag, index),
            "files": index[tag].get(evidence(tag, index), [])}


def families(index):
    c = collections.Counter(k.split("-")[0] for k in index)
    return c.most_common()


def register(path=REGISTER):
    """The recorded statements and statuses, keyed by id.

    Carries only what scanning CANNOT establish: what the claim says, whether
    it holds, and why not when it does not. Where it is written and what can
    make it fail are derived -- recording those here too would be a second
    authority over the same facts.
    """
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return {c["id"]: c for c in json.load(fh)["claims"]}


def status_report(index=None, reg=None):
    """Join the derived index with the register. Every finding is actionable.

    UNSUPPORTED_LIVE is the one that makes this more than bookkeeping: a claim
    cannot be recorded `live` when nothing in the tree can make it fail. That
    is not a live claim, it is an untested one, and its status is `open`.
    """
    index = scan() if index is None else index
    reg = register() if reg is None else reg
    known_causes = set(causes())
    out = {k: [] for k in ("UNSUPPORTED_LIVE", "MISSING_BECAUSE",
                           "MISSING_SALVAGE", "BAD_CAUSE",
                           "ORPHANED", "UNREGISTERED", "BAD_STATUS")}
    for cid, c in reg.items():
        if cid not in index:
            out["ORPHANED"].append(cid)
            continue
        if c["status"] not in STATUSES:
            out["BAD_STATUS"].append(cid)
        if c["status"] == "live" and evidence(cid, index) == "PROSE":
            out["UNSUPPORTED_LIVE"].append(cid)
        if c["status"] in ("dead", "superseded") and not c.get("because"):
            out["MISSING_BECAUSE"].append(cid)
        sv = c.get("salvage")
        if c["status"] == "dead" and not (sv and sv.get("keep")):
            # The anti-waste rule. Being wrong is expensive; refusing to
            # record what survives it is throwing away the return.
            out["MISSING_SALVAGE"].append(cid)
        if sv and known_causes and sv.get("cause") not in known_causes:
            out["BAD_CAUSE"].append(cid)
    for cid in index:
        if cid not in reg:
            out["UNREGISTERED"].append(cid)
    return {k: sorted(v) for k, v in out.items()}


# Which folder owns which family. Negentropic is absent on purpose: it has
# NEG_CLAIMS.md, which is the SOURCE this register parses, and generating a
# second table there would invert the authority.
FAMILY_HOME = {
    "ER": "Silicon", "KEA": "Silicon", "SEED": "Silicon", "R2": "Silicon",
    "FAB": "Silicon", "BRG": "Silicon", "EPG": "Silicon", "SIL": "Silicon",
    "TTM": "Silicon", "FP": "Silicon",
    "GIES": "GEIS", "FCL": "field",
    "VAC": "experiments/silicon_speculative",
    "ATT": "experiments/silicon_speculative",
    "TOP": "experiments/silicon_speculative",
    "VOR": "experiments/silicon_speculative",
}

GENERATED_HEADER = """<!-- GENERATED by claims_index.py render -- do not edit.
     Statements and statuses come from CLAIMS_REGISTER.json.
     Evidence class and file lists are SCANNED, not stored.
     Regenerate: python claims_index.py render -->

"""


def render(root=ROOT, write=True):
    """Write a CLAIMS.md into each folder that owns one or more families.

    Grouped by FOLDER, not by family. The first version keyed the output path
    on the family, so Silicon -- which owns ten of them -- ended up with only
    the last one written.

    Generated, so the folders get their table without becoming a second
    authority over what the claims say. Unregistered rows are included and
    marked, because a folder table that silently omitted them would read as
    complete.
    """
    idx, reg = scan(root), register()
    fams = collections.defaultdict(list)
    for cid in idx:
        fams[cid.split("-")[0]].append(cid)
    homes = collections.defaultdict(list)
    for fam, home in FAMILY_HOME.items():
        if fams.get(fam):
            homes[home].append(fam)
    written = {}
    for home, famlist in sorted(homes.items()):
        lines = [GENERATED_HEADER + "# Claims owned by `%s`" % home, ""]
        tot = rec = 0
        for fam in sorted(famlist):
            ids = sorted(fams[fam])
            lines += ["## %s" % fam, "",
                      "| id | statement | status | names | can fail via | "
                      "salvage |",
                      "|----|-----------|--------|-------|--------------|"
                      "---------|"]
            for cid in ids:
                c, ev = reg.get(cid), evidence(cid, idx)
                tot += 1
                if c:
                    rec += 1
                    sv = c.get("salvage") or {}
                    cell = ("**%s** — %s" % (sv["cause"],
                                             sv["keep"].replace("|", "\\|"))
                            if sv else "")
                    lines.append("| %s | %s | %s | %s | %s | %s |"
                                 % (cid, c["statement"].replace("|", "\\|"),
                                    c["status"], c["names"], ev, cell))
                else:
                    lines.append("| %s | _no recorded statement_ | "
                                 "unregistered | - | %s | |" % (cid, ev))
            lines.append("")
        lines += ["%d of %d recorded. `python claims_index.py status` checks "
                  "that nothing is marked live which nothing can falsify."
                  % (rec, tot), ""]
        body = "\n".join(lines)
        written[os.path.join(home, "CLAIMS.md")] = body
        if write and os.path.isdir(os.path.join(root, home)):
            with open(os.path.join(root, home, "CLAIMS.md"), "w",
                      encoding="utf-8") as fh:
                fh.write(body)
    return written


def by_family(reg=None):
    reg = register() if reg is None else reg
    fam = collections.defaultdict(list)
    for c in reg.values():
        fam[c["family"]].append(c)
    return {k: sorted(v, key=lambda c: c["id"]) for k, v in sorted(fam.items())}


# ---------------------------------------------------------------------
def main(argv):
    cmd = argv[1] if len(argv) > 1 else "index"
    idx = scan()
    by = index_by_class(idx)
    if cmd == "index":
        print("CLAIM INDEX  --  %d ids, scanned not maintained" % len(idx))
        print("  classified by what can make each one FAIL, strongest first")
        print()
        for c in CLASSES:
            ids = by.get(c, [])
            print("  %-10s %3d   %s" % (c, len(ids), ", ".join(ids[:12])
                                        + (" ..." if len(ids) > 12 else "")))
        print()
        n_exec = sum(len(by.get(c, [])) for c in ("FALSIFIER", "NAMED_IN_TEST"))
        print("  %d of %d claims have something executable pointed at them."
              % (n_exec, len(idx)))
        print("  python claims_index.py prose   # the ones that do not")
    elif cmd == "prose":
        ids = by.get("PROSE", [])
        print("WRITTEN DOWN, NOTHING EXECUTES AGAINST IT  (%d)" % len(ids))
        print("  Not an error. Bench work nobody has run, and definitions,")
        print("  live here legitimately. It is a state worth being able to see.")
        print()
        for cid in ids:
            print("  %-10s %s" % (cid, ", ".join(idx[cid]["PROSE"][:3])))
    elif cmd == "show" and len(argv) > 2:
        cid = argv[2]
        if cid not in idx:
            print("no such claim id: %s" % cid)
            return 1
        print("%s  --  %s" % (cid, evidence(cid, idx)))
        for c in CLASSES:
            for f in idx[cid].get(c, []):
                print("  %-10s %s" % (c, f))
    elif cmd == "status":
        reg = register()
        rep = status_report(idx, reg)
        counts = collections.Counter(c["status"] for c in reg.values())
        names = collections.Counter(c["names"] for c in reg.values())
        print("REGISTER  --  %d of %d claims carry a recorded statement"
              % (len(reg), len(idx)))
        print("  status: " + ", ".join("%s %d" % kv for kv in counts.most_common()))
        print("  the id names: " + ", ".join("%s %d" % kv
                                             for kv in names.most_common()))
        print()
        bad = 0
        for k in ("UNSUPPORTED_LIVE", "MISSING_BECAUSE", "MISSING_SALVAGE",
                  "BAD_CAUSE", "ORPHANED", "BAD_STATUS"):
            if rep[k]:
                bad += len(rep[k])
                print("  %-18s %s" % (k, ", ".join(rep[k])))
        if not bad:
            print("  no contradictions: nothing is recorded live that nothing "
                  "can falsify, and nothing died without saying what survives.")
        sv = [c for c in reg.values() if c.get("salvage")]
        print()
        print("  %d of %d carry salvage -- what is reusable from being wrong."
              % (len(sv), len(reg)))
        print("  python claims_index.py salvage")
        print()
        print("  %d unregistered. python claims_index.py unregistered"
              % len(rep["UNREGISTERED"]))
        return 1 if bad else 0
    elif cmd == "salvage":
        reg = register()
        cz = causes()
        want = argv[2] if len(argv) > 2 else None
        groups = collections.defaultdict(list)
        for c in reg.values():
            if c.get("salvage"):
                groups[c["salvage"]["cause"]].append(c)
        if want and want not in groups:
            print("no salvage recorded under %r. causes: %s"
                  % (want, ", ".join(sorted(groups))))
            return 1
        total = sum(len(v) for v in groups.values())
        print("WHAT SURVIVES BEING WRONG  (%d records)" % total)
        print("  A claim dies of something, and the cause decides what is")
        print("  recyclable. Being wrong is expensive -- the arithmetic, the")
        print("  bound, the sound half of the design and the error's own")
        print("  general form are the return on it.")
        for cause in sorted(groups):
            if want and cause != want:
                continue
            print()
            print("== %s  (%d)" % (cause, len(groups[cause])))
            print("   %s" % cz.get(cause, ""))
            for c in sorted(groups[cause], key=lambda x: x["id"]):
                sv = c["salvage"]
                print()
                print("   %-8s %s" % (c["id"], c["statement"]))
                if sv.get("killed"):
                    print("            KILLED  %s" % sv["killed"])
                print("            KEEP    %s" % sv["keep"])
                if sv.get("principle"):
                    print("            SHAPE   %s" % sv["principle"])
    elif cmd == "unregistered":
        rep = status_report(idx)
        print("IN THE TREE, NO RECORDED STATEMENT  (%d)" % len(rep["UNREGISTERED"]))
        print("  Each is a claim someone wrote and nobody has said whether it")
        print("  still holds. Not invented here -- writing 99 statements I had")
        print("  not verified would be the defect this register exists against.")
        print()
        for cid in rep["UNREGISTERED"]:
            print("  %-10s %-14s %s" % (cid, evidence(cid, idx),
                                        ", ".join(idx[cid]["PROSE"][:2])))
    elif cmd == "render":
        w = render()
        for path in sorted(w):
            print("  wrote %s" % path)
        print()
        print("  generated from CLAIMS_REGISTER.json + the scan. "
              "Negentropic/NEG_CLAIMS.md is the source for NEG/TRI and is "
              "not overwritten.")
    elif cmd == "families":
        for fam, n in families(idx):
            print("  %-8s %3d" % (fam, n))
    else:
        print("usage: claims_index.py [index | prose | status | "
              "unregistered | salvage [CAUSE] | render | show ID | "
              "families]")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
